name: thepaper_starter
description: Test app for The Paper

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# info.plist used to be bundle version = $(FLUTTER_BUILD_NUMBER)
version: 1.0.3+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.15.3
  # firebase_auth: ^0.16.0
  # google_sign_in: ^4.4.2
  google_sign_in: ^4.5.1
  provider: ^4.0.1
  rxdart: ^0.23.1
  cloud_firestore: ^0.13.0+1
  # cloud_firestore: ^0.13.5
  intl: ^0.16.0
  auto_route: ^0.2.2
  cached_network_image: ^2.1.0+1
  animated_stream_list: ^1.1.0
  flutter_facebook_login: ^3.0.0
  expandable: ^4.1.3
  google_fonts: ^1.0.0
  timeago: ^2.0.26
  html: ^0.14.0+3
  firebase_remote_config: ^0.3.0+3
  package_info: ^0.4.0+17
  url_launcher: ^5.4.10
  algolia: ^0.1.7
  flappy_search_bar: ^1.7.2
  flutter_html: ^1.0.0
  firebase_messaging: ^6.0.16
  grouped_list: ^3.1.0
  modal_bottom_sheet: ^0.1.6+1
  amplitude_flutter: ^2.1.1

  # firestore_service:
  #   git:
  #     url: https://github.com/bizz84/codewithandrea_flutter_packages
  #     path: packages/firestore_service




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  auto_route_generator: ^0.2.2
  build_runner: ^1.7.3
  random_string: ^2.0.0
  flutter_driver:
    sdk: flutter 
  test: any
  flutter_launcher_icons: "^0.7.5"
  

# For flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
    - assets/images/GreenMorty.jpg
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: Goldman
      fonts:
        - asset: fonts/GS/GoldmanSans_A_Bd.ttf
        - asset: fonts/GS/GoldmanSans_A_BdIt.ttf
        - asset: fonts/GS/GoldmanSans_A_Blk.ttf
        - asset: fonts/GS/GoldmanSans_A_lt.ttf
        - asset: fonts/GS/GoldmanSans_A_Lt.ttf
        - asset: fonts/GS/GoldmanSans_A_Md.ttf
        - asset: fonts/GS/GoldmanSans_A_MdIt.ttf
        - asset: fonts/GS/GoldmanSans_A_Rg.ttf
        - asset: fonts/GS/GoldmanSans_A_Th.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
