name: thepaper_starter
description: Test app for The Paper

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# info.plist used to be bundle version = $(FLUTTER_BUILD_NUMBER)
version: 1.0.3+1
publish_to: none

environment:
  sdk: ">=2.11.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  # firebase_auth: ^0.15.3
  firebase_auth: ^3.0.1
  # google_sign_in: ^4.4.2
  google_sign_in: ^5.0.5
  provider: ^5.0.0
  rxdart: ^0.27.1
  # cloud_firestore: ^0.13.0+1
  # cloud_firestore: ^0.14.0+2
  cloud_firestore: ^2.4.0
  firebase_core: ^1.4.0
  intl: ^0.17.0
  # auto_route: ^0.2.2
  auto_route: ^2.2.0
  cached_network_image: ^3.1.0 #^2.3.2+1
  animated_stream_list:
    git:
      url: git://github.com/jackstefansky/animated-stream-list.git
      # path: packages/firebase_messaging
  expandable: ^5.0.1
  google_fonts: ^2.1.0
  timeago: ^3.1.0
  html: ^0.15.0
  flutter_html: ^2.1.1
  firebase_remote_config: ^0.10.0+3
  package_info: ^2.0.2
  url_launcher: ^6.0.9
  # algolia: ^0.1.7
  algolia: ^1.0.1
  flappy_search_bar:
    git:
      url: git://github.com/harryjjacobs/flappy_search_bar.git
      
  # firebase_messaging: ^6.0.16
  # firebase_messaging: ^7.0.0
  # firebase_messaging:
  #   git:
  #     url: git://github.com/preetjdp/flutterfire.git
  #     ref: fix-3312
  #     path: packages/firebase_messaging
  grouped_list: ^4.1.0
  modal_bottom_sheet: ^2.0.0
  amplitude_flutter: ^3.2.1
  # firebase_crashlytics: ^2.1.1
  meta: ^1.7.0
  cupertino_icons: ^1.0.3


dependency_overrides:
  # For firebase_messaging
  # image: last_version
  # xml: last_version

#   platform: 3.0.0-nullsafety.1

  # firestore_service:
  #   git:
  #     url: https://github.com/bizz84/codewithandrea_flutter_packages
  #     path: packages/firestore_service




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  random_string: ^2.3.1
  flutter_driver:
    sdk: flutter 
  test: ^1.17.10
  # flutter_launcher_icons: "^0.9.1"
  

# For flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
    - assets/images/GreenMorty.jpg
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: Goldman
      fonts:
        - asset: fonts/GS/GoldmanSans_A_Bd.ttf
        - asset: fonts/GS/GoldmanSans_A_BdIt.ttf
        - asset: fonts/GS/GoldmanSans_A_Blk.ttf
        - asset: fonts/GS/GoldmanSans_A_lt.ttf
        - asset: fonts/GS/GoldmanSans_A_Lt.ttf
        - asset: fonts/GS/GoldmanSans_A_Md.ttf
        - asset: fonts/GS/GoldmanSans_A_MdIt.ttf
        - asset: fonts/GS/GoldmanSans_A_Rg.ttf
        - asset: fonts/GS/GoldmanSans_A_Th.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
