import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:thepaper_starter/services/analytics_service.dart';
import 'package:thepaper_starter/services/firestore_database.dart';
import 'package:thepaper_starter/services/firebase_auth_service.dart';

/// Used to create user-dependent objects that need to be accessible by all widgets.
/// This widgets should live above the [MaterialApp].
/// See [AuthWidget], a descendant widget that consumes the snapshot generated by this builder.
class AuthWidgetBuilder extends StatelessWidget {
  const AuthWidgetBuilder(
      {Key key, @required this.builder, @required this.databaseBuilder})
      : super(key: key);
  final Widget Function(BuildContext, AsyncSnapshot<AppUser>) builder;
  final FirestoreDatabase Function(BuildContext context, String uid)
      databaseBuilder;

  @override
  Widget build(BuildContext context) {
    final authService =
        Provider.of<FirebaseAuthService>(context, listen: false);

    return StreamBuilder<AppUser>(
      stream: authService.authStateChanges(),
      builder: (BuildContext context, AsyncSnapshot<AppUser> snapshot) {
        final AppUser user = snapshot.data;
        if (user != null) {

          if(snapshot.connectionState == ConnectionState.active){
            final analyticsService = Provider.of<AnalyticsService>(context, listen: false);
            analyticsService.identifyUser(user.uid, user.displayName);
          }
          return MultiProvider(
            providers: [
              Provider<AppUser>.value(value: user),
              Provider<FirestoreDatabase>(
                create: (context) => databaseBuilder(context, user.uid),
              ),
              // NOTE: Any other user-bound providers here can be added here
            ],
            child: builder(context, snapshot),
          );
        }
        return builder(context, snapshot);
      },
    );
  }
}
